// ==========================================
// ★ Copeak 多言語化辞書データ (i18n)
// ==========================================
const i18n = {
    // 🇯🇵 日本語（デフォルト）
    "ja": {
        "head_title": "Copeak - 英語音読・シャドーイング練習ツール",
        "nav_my_library": "My Library",
        "warning_title": "データの保存に関する重要なお願い",
        "warning_ipad_bold": "iPad / スマホの方:",
        "warning_ipad_desc": "最初にブラウザのメニューから「ホーム画面に追加」を行い、必ずそのアイコンからアプリを開いてください。",
        "warning_pc_bold": "PCの方:",
        "warning_pc_desc": "ブックマークに登録し、常に同じブラウザを使用してください。",
        "teacher_title": "教員専用設定：成績回収システムの準備",
        "teacher_desc": "全国の先生方がこのシステムを使うための2ステップです。一度設定すれば、以後は共有リンクに自動で成績送信機能が付与されます。",
        "teacher_step1_title": "フォームの複製",
        "teacher_step1_desc": "以下のボタンから成績回収用のGoogleフォーム（ひな形）をご自身のGoogleドライブにコピーしてください。（※質問項目は変更しないでください）",
        "teacher_step1_btn": "マスターフォームをコピー",
        "teacher_step2_title": "URLの登録",
        "teacher_step2_desc": "コピーしたフォームを送信モードにし、回答用のURL（.../viewform）を下に貼り付けて保存します。",
        "teacher_step2_btn": "保存",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "Create / Edit Material",
        "form_label_title": "Title",
        "form_placeholder_title": "例: Steve Jobs Speech",
        "form_label_language": "Language",
        "form_label_audio": "Audio File (Optional)",
        "form_audio_saved": "音声はすでに保存されています",
        "form_label_text": "Target Text (学習テキスト)",
        "form_placeholder_eng": "英語などのスクリプトを貼り付け",
        "form_label_translation": "Translation (日本語訳など)",
        "form_placeholder_jpn": "母語での訳を貼り付け (任意)",
        "form_btn_cancel": "Cancel",
        "form_btn_save": "Save to Library",
        "playlist_title": "Playlist",
        "footer_picspeak": "PicSpeak (スピーキング)",
        "footer_vocadash": "VocaDash (単語学習)",
        "footer_guide": "活用ガイド",
        "footer_dev": "開発者について",
        "footer_teacher": "教員用メニュー",
        "footer_terms": "利用規約",
        "footer_privacy": "プライバシーポリシー",
        "learn_back": "Back",
        "learn_share": "共有",
        "tab_read": "Read",
        "tab_paced": "Paced",
        "tab_vanish": "Vanish",
        "tab_shadow": "Shadow",
        "btn_ai_voice": "AI音声を再生",
        "score_accuracy": "Accuracy",
        "score_wpm": "WPM",
        "score_comp": "Comprehension",
        "score_feedback": "Learning Feedback",
        "btn_submit_score": "先生に成績を提出する（振り返り入力へ）",
        "label_your_voice": "Your Voice",
        "msg_press_start": "※Press START to begin",
        "label_target_text": "Target Text",
        "btn_show_translation": "訳を表示",
        "label_blank_level": "Blank Level (空欄の割合)",
        "label_target_wpm": "目標WPM設定",
        "label_translation": "Translation",
        "btn_start_text": "START",
        "sidebar_playlist": "Playlist",
        "chart_title": "Learning Progress",
        "chart_desc": "※日々の反復がスコアアップの鍵です！",
        "profile_title": "プロフィール登録",
        "profile_desc": "成績を送信するために、あなたの情報を登録してください。（この端末に保存されます）",
        "profile_class": "クラス",
        "profile_placeholder_class": "例: 1-A",
        "profile_num": "出席番号",
        "profile_placeholder_num": "例: 15",
        "profile_name": "氏名",
        "profile_placeholder_name": "例: 岡崎 太郎",
        "profile_save": "保存して始める",
        "ref_title": "先生に成績を送信",
        "ref_desc": "今日の練習の振り返り（工夫した点、難しかった点など）",
        "ref_placeholder_text": "例: イントネーションを意識してシャドーイングしました。",
        "ref_cancel": "キャンセル",
        "ref_submit": "この内容で送信する",
        "wpm_guide_title": "WPMの目安",
        "wpm_guide_desc": "※WPM (Words Per Minute) ＝ 1分間に読む単語数",
        "wpm_80": "ゆっくり (初心者)",
        "wpm_100": "標準的 (中学生レベル)",
        "wpm_120": "流暢 (高校生・日常会話)",
        "wpm_150": "速い (ニュース・TOEIC)",
        "wpm_180": "超特急 (ネイティブの早口)",
        "btn_close": "閉じる",
        "mode_guide_title": "Copeak 4-Step Learning Guide",
        "mode_guide_warning": "いきなり「Paced」や「Vanish」を行っても学習効果はありません。英文の内容を完全に理解し、Step 1 から順番に負荷を上げていきましょう。",
        "mode_tag_1": "導入・意味理解",
        "mode_sla": "🔬 SLA科学的根拠:",
        "mode_desc_1": "「Form-Meaning Mapping（形式と意味の結びつけ）」。文字と音声、そして「意味」を脳内で連結させる最初の土台作りです。",
        "mode_check": "🤔 内省チェック:",
        "mode_check_1": "「英文の意味を100%理解し、つっかえずにスラスラ読めているか？」",
        "mode_tag_2": "流暢さ・自動化",
        "mode_desc_2": "「Automatization（自動化）」。強制的なペースで「返り読み」を物理的に防ぎ、英語を英語の語順のまま処理するスピードを鍛えます。",
        "mode_check_2": "「日本語に訳さず理解できているか？スピードに焦って発音が雑になっていないか？」",
        "mode_tag_3": "記憶定着・内在化",
        "mode_desc_3": "「Retrieval Practice（検索練習）」。文字という視覚ヒントを奪い、ワーキングメモリに負荷をかけることで長期記憶への定着を促します。",
        "mode_check_3": "「単なる丸暗記ではなく、文脈や文法ルールから次の単語を予測して発話できているか？」",
        "mode_tag_4": "音韻処理の極致",
        "mode_desc_4": "「Phonological Loop（音韻ループ）の強化」。ネイティブのプロソディ（抑揚・リズム）を完全に模倣し、音声処理を極限まで自動化させます。",
        "mode_check_4": "「手本と声が完全に重なっているか？音声に集中しながら意味も頭に浮かんでいるか？」",
        "btn_start_learning": "理解して学習を始める"
    },

    // 🇺🇸 英語
    "en": {
        "head_title": "Copeak - English Shadowing & Reading Tool",
        "nav_my_library": "My Library",
        "warning_title": "Important Notice for Saving Data",
        "warning_ipad_bold": "iPad / Mobile users:",
        "warning_ipad_desc": "Please tap 'Add to Home Screen' from your browser menu first, and always open the app from that icon.",
        "warning_pc_bold": "PC users:",
        "warning_pc_desc": "Please bookmark this page and always use the same browser.",
        "teacher_title": "Teacher Settings: Score Collection Setup",
        "teacher_desc": "2 steps to set up the system. Once configured, a score submission feature will be automatically added to your shared links.",
        "teacher_step1_title": "Duplicate Form",
        "teacher_step1_desc": "Click the button below to copy the master Google Form to your Drive. (*Please do not edit the questions)",
        "teacher_step1_btn": "Copy Master Form",
        "teacher_step2_title": "Register URL",
        "teacher_step2_desc": "Open the copied form in 'Send' mode, paste the response URL (.../viewform) below, and save.",
        "teacher_step2_btn": "Save",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "Create / Edit Material",
        "form_label_title": "Title",
        "form_placeholder_title": "e.g., Steve Jobs Speech",
        "form_label_language": "Language",
        "form_label_audio": "Audio File (Optional)",
        "form_audio_saved": "Audio is already saved",
        "form_label_text": "Target Text",
        "form_placeholder_eng": "Paste the target script here",
        "form_label_translation": "Translation",
        "form_placeholder_jpn": "Paste the translation (Optional)",
        "form_btn_cancel": "Cancel",
        "form_btn_save": "Save to Library",
        "playlist_title": "Playlist",
        "footer_picspeak": "PicSpeak (Speaking)",
        "footer_vocadash": "VocaDash (Vocabulary)",
        "footer_guide": "User Guide",
        "footer_dev": "About Developer",
        "footer_teacher": "Teacher Menu",
        "footer_terms": "Terms of Use",
        "footer_privacy": "Privacy Policy",
        "learn_back": "Back",
        "learn_share": "Share",
        "tab_read": "Read",
        "tab_paced": "Paced",
        "tab_vanish": "Vanish",
        "tab_shadow": "Shadow",
        "btn_ai_voice": "Play AI Voice",
        "score_accuracy": "Accuracy",
        "score_wpm": "WPM",
        "score_comp": "Comprehension",
        "score_feedback": "Learning Feedback",
        "btn_submit_score": "Submit Score to Teacher (Reflection)",
        "label_your_voice": "Your Voice",
        "msg_press_start": "*Press START to begin",
        "label_target_text": "Target Text",
        "btn_show_translation": "Show Translation",
        "label_blank_level": "Blank Level",
        "label_target_wpm": "Target WPM",
        "label_translation": "Translation",
        "btn_start_text": "START",
        "sidebar_playlist": "Playlist",
        "chart_title": "Learning Progress",
        "chart_desc": "*Daily practice is the key to a higher score!",
        "profile_title": "Profile Registration",
        "profile_desc": "Please register your information to submit scores. (Saved locally on this device)",
        "profile_class": "Class",
        "profile_placeholder_class": "e.g., 1-A",
        "profile_num": "Student Number",
        "profile_placeholder_num": "e.g., 15",
        "profile_name": "Name",
        "profile_placeholder_name": "e.g., John Doe",
        "profile_save": "Save and Start",
        "ref_title": "Submit Score",
        "ref_desc": "Reflection on today's practice (What went well, what was difficult, etc.)",
        "ref_placeholder_text": "e.g., I focused on my intonation while shadowing...",
        "ref_cancel": "Cancel",
        "ref_submit": "Submit Now",
        "wpm_guide_title": "WPM Guide",
        "wpm_guide_desc": "*WPM (Words Per Minute)",
        "wpm_80": "Slow (Beginner)",
        "wpm_100": "Standard (Intermediate)",
        "wpm_120": "Fluent (Daily Conversation)",
        "wpm_150": "Fast (News/TOEIC)",
        "wpm_180": "Super Fast (Native speed)",
        "btn_close": "Close",
        "mode_guide_title": "Copeak 4-Step Learning Guide",
        "mode_guide_warning": "Jumping straight to 'Paced' or 'Vanish' won't be effective. Understand the text perfectly first, then increase the load step by step.",
        "mode_tag_1": "Introduction / Meaning",
        "mode_sla": "🔬 SLA Basis:",
        "mode_desc_1": "'Form-Meaning Mapping'. The foundation of connecting text, sound, and meaning in your brain.",
        "mode_check": "🤔 Reflection Check:",
        "mode_check_1": "'Do I understand the meaning 100% and can I read it smoothly without stumbling?'",
        "mode_tag_2": "Fluency / Automatization",
        "mode_desc_2": "'Automatization'. A forced visual pace prevents regression, training your brain to process English in its natural word order.",
        "mode_check_2": "'Am I understanding it in English without translating? Is my pronunciation getting sloppy due to speed?'",
        "mode_tag_3": "Retention / Internalization",
        "mode_desc_3": "'Retrieval Practice'. By removing visual hints, we force your working memory to recall words, cementing them into long-term memory.",
        "mode_check_3": "'Am I predicting the next word from context/grammar, rather than just rote memorization?'",
        "mode_tag_4": "Ultimate Phonological Loop",
        "mode_desc_4": "'Phonological Loop Enhancement'. Mimicking the native prosody fully automates your speech perception, boosting both speaking and listening.",
        "mode_check_4": "'Is my voice perfectly overlapping with the model? Am I imagining the meaning while focusing on the sound?'",
        "btn_start_learning": "I understand, let's start"
    },

    // 🇹🇼 台湾語（繁体字）
    "zh-TW": {
        "head_title": "Copeak - 英語跟讀與朗讀練習工具",
        "nav_my_library": "我的素材庫",
        "warning_title": "關於資料保存的重要通知",
        "warning_ipad_bold": "iPad / 手機用戶:",
        "warning_ipad_desc": "請先從瀏覽器選單點擊「加入主畫面」，並且務必從該圖示開啟應用程式。",
        "warning_pc_bold": "電腦用戶:",
        "warning_pc_desc": "請將此頁面加入書籤，並始終使用相同的瀏覽器。",
        "teacher_title": "教師專用：成績收集系統設定",
        "teacher_desc": "設定系統只需兩個步驟。設定完成後，您的分享連結將自動附帶成績提交功能。",
        "teacher_step1_title": "複製表單",
        "teacher_step1_desc": "點擊下方按鈕將成績收集用的 Google 表單複製到您的雲端硬碟。（※請勿修改問題項目）",
        "teacher_step1_btn": "複製主表單",
        "teacher_step2_title": "註冊 URL",
        "teacher_step2_desc": "以「傳送」模式打開複製的表單，將回覆用的 URL（.../viewform）貼在下方並保存。",
        "teacher_step2_btn": "保存",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "創建 / 編輯素材",
        "form_label_title": "標題",
        "form_placeholder_title": "例: 賈伯斯演講",
        "form_label_language": "語言",
        "form_label_audio": "音檔 (選填)",
        "form_audio_saved": "音檔已保存",
        "form_label_text": "學習文本",
        "form_placeholder_eng": "在此貼上英語講稿",
        "form_label_translation": "翻譯",
        "form_placeholder_jpn": "在此貼上母語翻譯 (選填)",
        "form_btn_cancel": "取消",
        "form_btn_save": "保存至素材庫",
        "playlist_title": "播放清單",
        "footer_picspeak": "PicSpeak (口說)",
        "footer_vocadash": "VocaDash (單字)",
        "footer_guide": "使用指南",
        "footer_dev": "關於開發者",
        "footer_teacher": "教師選單",
        "footer_terms": "服務條款",
        "footer_privacy": "隱私政策",
        "learn_back": "返回",
        "learn_share": "分享",
        "tab_read": "朗讀",
        "tab_paced": "配速",
        "tab_vanish": "消失",
        "tab_shadow": "跟讀",
        "btn_ai_voice": "播放 AI 語音",
        "score_accuracy": "準確度",
        "score_wpm": "WPM",
        "score_comp": "理解度",
        "score_feedback": "學習反饋",
        "btn_submit_score": "將成績提交給老師（填寫反思）",
        "label_your_voice": "您的語音",
        "msg_press_start": "※按 START 開始",
        "label_target_text": "目標文本",
        "btn_show_translation": "顯示翻譯",
        "label_blank_level": "挖空難度",
        "label_target_wpm": "目標 WPM 設定",
        "label_translation": "翻譯",
        "btn_start_text": "START",
        "sidebar_playlist": "播放清單",
        "chart_title": "學習進度",
        "chart_desc": "※每天的反覆練習是提高分數的關鍵！",
        "profile_title": "註冊個人資料",
        "profile_desc": "請註冊您的資訊以提交成績。（資料將保存在此設備上）",
        "profile_class": "班級",
        "profile_placeholder_class": "例: 1-A",
        "profile_num": "座號",
        "profile_placeholder_num": "例: 15",
        "profile_name": "姓名",
        "profile_placeholder_name": "例: 王小明",
        "profile_save": "保存並開始",
        "ref_title": "提交成績給老師",
        "ref_desc": "今日練習的反思（做得好的地方、困難的地方等）",
        "ref_placeholder_text": "例: 練習跟讀時，我特別注意了語調...",
        "ref_cancel": "取消",
        "ref_submit": "確認提交",
        "wpm_guide_title": "WPM 參考指標",
        "wpm_guide_desc": "※WPM (Words Per Minute) ＝ 每分鐘閱讀字數",
        "wpm_80": "緩慢 (初學者)",
        "wpm_100": "標準 (國中程度)",
        "wpm_120": "流利 (高中/日常對話)",
        "wpm_150": "快速 (新聞/多益)",
        "wpm_180": "極快 (母語人士語速)",
        "btn_close": "關閉",
        "mode_guide_title": "Copeak 4步驟學習指南",
        "mode_guide_warning": "直接進行「配速」或「消失」模式是無效的。請先完全理解文本，然後循序漸進地增加難度。",
        "mode_tag_1": "導入與理解",
        "mode_sla": "🔬 SLA 科學依據:",
        "mode_desc_1": "「形義連結」。在腦中將文字、聲音與意義建立連結的基礎步驟。",
        "mode_check": "🤔 反思檢查:",
        "mode_check_1": "「我是否 100% 理解意思，並且能流暢閱讀而不卡頓？」",
        "mode_tag_2": "流利度與自動化",
        "mode_desc_2": "「自動化」。強制性的視覺配速可防止回視，訓練大腦以英語的自然語序處理資訊。",
        "mode_check_2": "「我是否能直接用英語理解而不需要翻譯？發音是否因為速度變快而變得模糊？」",
        "mode_tag_3": "記憶與內化",
        "mode_desc_3": "「檢索練習」。藉由移除視覺提示，強迫工作記憶回想單字，進而鞏固至長期記憶。",
        "mode_check_3": "「我是根據上下文和文法規則預測下一個字，還是只是死記硬背？」",
        "mode_tag_4": "終極語音處理",
        "mode_desc_4": "「強化語音迴路」。完全模仿母語人士的韻律，讓語音處理達到極致自動化。",
        "mode_check_4": "「我的聲音是否與示範音檔完全重合？專注於聲音的同時，腦海中是否浮現了句意？」",
        "btn_start_learning": "我明白了，開始學習"
    },

    // 🇻🇳 ベトナム語
    "vi": {
        "head_title": "Copeak - Công cụ luyện đọc và Shadowing tiếng Anh",
        "nav_my_library": "Thư viện của tôi",
        "warning_title": "Lưu ý quan trọng về việc lưu dữ liệu",
        "warning_ipad_bold": "Người dùng iPad / Điện thoại:",
        "warning_ipad_desc": "Vui lòng chọn 'Thêm vào Màn hình chính' từ menu trình duyệt trước, và luôn mở ứng dụng từ biểu tượng đó.",
        "warning_pc_bold": "Người dùng PC:",
        "warning_pc_desc": "Vui lòng đánh dấu (bookmark) trang này và luôn sử dụng cùng một trình duyệt.",
        "teacher_title": "Cài đặt cho giáo viên: Thu thập điểm số",
        "teacher_desc": "2 bước để thiết lập hệ thống. Sau khi thiết lập, tính năng gửi điểm sẽ tự động được thêm vào liên kết chia sẻ của bạn.",
        "teacher_step1_title": "Sao chép Biểu mẫu",
        "teacher_step1_desc": "Nhấp vào nút bên dưới để sao chép Google Form thu thập điểm vào Drive của bạn. (*Vui lòng không chỉnh sửa các câu hỏi)",
        "teacher_step1_btn": "Sao chép Biểu mẫu Gốc",
        "teacher_step2_title": "Đăng ký URL",
        "teacher_step2_desc": "Mở biểu mẫu đã sao chép ở chế độ 'Gửi', dán URL phản hồi (.../viewform) xuống dưới và lưu lại.",
        "teacher_step2_btn": "Lưu",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "Tạo / Chỉnh sửa Bài học",
        "form_label_title": "Tiêu đề",
        "form_placeholder_title": "VD: Bài phát biểu của Steve Jobs",
        "form_label_language": "Ngôn ngữ",
        "form_label_audio": "Tệp âm thanh (Tùy chọn)",
        "form_audio_saved": "Âm thanh đã được lưu",
        "form_label_text": "Văn bản Mục tiêu",
        "form_placeholder_eng": "Dán kịch bản tiếng Anh vào đây",
        "form_label_translation": "Bản dịch",
        "form_placeholder_jpn": "Dán bản dịch tiếng mẹ đẻ (Tùy chọn)",
        "form_btn_cancel": "Hủy",
        "form_btn_save": "Lưu vào Thư viện",
        "playlist_title": "Danh sách phát",
        "footer_picspeak": "PicSpeak (Nói)",
        "footer_vocadash": "VocaDash (Từ vựng)",
        "footer_guide": "Hướng dẫn sử dụng",
        "footer_dev": "Về nhà phát triển",
        "footer_teacher": "Menu Giáo viên",
        "footer_terms": "Điều khoản sử dụng",
        "footer_privacy": "Chính sách bảo mật",
        "learn_back": "Quay lại",
        "learn_share": "Chia sẻ",
        "tab_read": "Đọc",
        "tab_paced": "Đọc theo nhịp",
        "tab_vanish": "Ẩn chữ",
        "tab_shadow": "Shadowing",
        "btn_ai_voice": "Phát giọng AI",
        "score_accuracy": "Độ chính xác",
        "score_wpm": "WPM",
        "score_comp": "Mức độ hiểu",
        "score_feedback": "Phản hồi học tập",
        "btn_submit_score": "Gửi điểm cho Giáo viên (Kèm đánh giá)",
        "label_your_voice": "Giọng của bạn",
        "msg_press_start": "*Nhấn START để bắt đầu",
        "label_target_text": "Văn bản Mục tiêu",
        "btn_show_translation": "Hiện Bản dịch",
        "label_blank_level": "Mức độ Ẩn",
        "label_target_wpm": "Mục tiêu WPM",
        "label_translation": "Bản dịch",
        "btn_start_text": "START",
        "sidebar_playlist": "Danh sách phát",
        "chart_title": "Tiến độ Học tập",
        "chart_desc": "*Thực hành hàng ngày là chìa khóa để điểm cao hơn!",
        "profile_title": "Đăng ký Hồ sơ",
        "profile_desc": "Vui lòng đăng ký thông tin của bạn để gửi điểm. (Được lưu cục bộ trên thiết bị này)",
        "profile_class": "Lớp",
        "profile_placeholder_class": "VD: 1-A",
        "profile_num": "Số báo danh",
        "profile_placeholder_num": "VD: 15",
        "profile_name": "Họ và tên",
        "profile_placeholder_name": "VD: Nguyễn Văn A",
        "profile_save": "Lưu và Bắt đầu",
        "ref_title": "Gửi Điểm số",
        "ref_desc": "Đánh giá buổi luyện tập hôm nay (Điều gì tốt, điều gì khó khăn...)",
        "ref_placeholder_text": "VD: Em đã tập trung vào ngữ điệu khi shadowing...",
        "ref_cancel": "Hủy",
        "ref_submit": "Gửi ngay",
        "wpm_guide_title": "Hướng dẫn về WPM",
        "wpm_guide_desc": "*WPM (Words Per Minute) = Số từ trên phút",
        "wpm_80": "Chậm (Người mới)",
        "wpm_100": "Tiêu chuẩn (Trung học)",
        "wpm_120": "Trôi chảy (Giao tiếp hàng ngày)",
        "wpm_150": "Nhanh (Tin tức/TOEIC)",
        "wpm_180": "Rất nhanh (Tốc độ bản xứ)",
        "btn_close": "Đóng",
        "mode_guide_title": "Hướng dẫn Học 4 Bước Copeak",
        "mode_guide_warning": "Bắt đầu ngay bằng 'Đọc theo nhịp' hoặc 'Ẩn chữ' sẽ không hiệu quả. Hãy hiểu bài 100% trước, sau đó tăng độ khó từng bước.",
        "mode_tag_1": "Giới thiệu / Ý nghĩa",
        "mode_sla": "🔬 Cơ sở Khoa học SLA:",
        "mode_desc_1": "'Ánh xạ Hình thức - Ý nghĩa'. Nền tảng để kết nối chữ viết, âm thanh và ý nghĩa trong não bộ.",
        "mode_check": "🤔 Tự kiểm tra:",
        "mode_check_1": "'Tôi đã hiểu 100% ý nghĩa và có thể đọc trôi chảy không vấp váp chưa?'",
        "mode_tag_2": "Trôi chảy / Tự động hóa",
        "mode_desc_2": "'Tự động hóa'. Tốc độ trực quan bắt buộc ngăn bạn đọc ngược, rèn luyện não xử lý tiếng Anh theo trật tự từ tự nhiên.",
        "mode_check_2": "'Tôi có đang hiểu bằng tiếng Anh mà không cần dịch không? Phát âm của tôi có bị mờ do đọc nhanh không?'",
        "mode_tag_3": "Ghi nhớ / Nội tâm hóa",
        "mode_desc_3": "'Thực hành Gợi nhớ'. Bằng cách loại bỏ gợi ý hình ảnh, trí nhớ làm việc phải chủ động nhớ lại từ, giúp củng cố trí nhớ dài hạn.",
        "mode_check_3": "'Tôi có đang dự đoán từ tiếp theo từ ngữ cảnh/ngữ pháp thay vì chỉ học thuộc lòng không?'",
        "mode_tag_4": "Xử lý Ngữ âm Tối ưu",
        "mode_desc_4": "'Tăng cường Vòng lặp Ngữ âm'. Việc bắt chước hoàn toàn ngữ điệu bản xứ giúp tự động hóa nhận thức âm thanh, tăng cường cả nói và nghe.",
        "mode_check_4": "'Giọng tôi có khớp hoàn toàn với mẫu không? Tôi có đang hình dung ý nghĩa trong khi tập trung vào âm thanh không?'",
        "btn_start_learning": "Tôi đã hiểu, bắt đầu thôi"
    },

    // 🇮🇩 インドネシア語
    "id": {
        "head_title": "Copeak - Alat Latihan Membaca & Shadowing Bahasa Inggris",
        "nav_my_library": "Perpustakaan Saya",
        "warning_title": "Pemberitahuan Penting Penyimpanan Data",
        "warning_ipad_bold": "Pengguna iPad / HP:",
        "warning_ipad_desc": "Silakan ketuk 'Tambahkan ke Layar Utama' dari menu browser Anda terlebih dahulu, dan selalu buka aplikasi dari ikon tersebut.",
        "warning_pc_bold": "Pengguna PC:",
        "warning_pc_desc": "Harap bookmark halaman ini dan selalu gunakan browser yang sama.",
        "teacher_title": "Pengaturan Guru: Sistem Pengumpulan Nilai",
        "teacher_desc": "2 langkah untuk menyiapkan sistem. Setelah diatur, fitur pengiriman nilai akan otomatis ditambahkan ke tautan yang Anda bagikan.",
        "teacher_step1_title": "Salin Formulir",
        "teacher_step1_desc": "Klik tombol di bawah untuk menyalin Google Form utama ke Drive Anda. (*Harap jangan mengedit pertanyaan)",
        "teacher_step1_btn": "Salin Formulir Utama",
        "teacher_step2_title": "Daftarkan URL",
        "teacher_step2_desc": "Buka formulir yang disalin dalam mode 'Kirim', tempel URL respons (.../viewform) di bawah ini, dan simpan.",
        "teacher_step2_btn": "Simpan",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "Buat / Edit Materi",
        "form_label_title": "Judul",
        "form_placeholder_title": "Cth: Pidato Steve Jobs",
        "form_label_language": "Bahasa",
        "form_label_audio": "File Audio (Opsional)",
        "form_audio_saved": "Audio sudah tersimpan",
        "form_label_text": "Teks Target",
        "form_placeholder_eng": "Tempel naskah bahasa Inggris di sini",
        "form_label_translation": "Terjemahan",
        "form_placeholder_jpn": "Tempel terjemahan bahasa asli (Opsional)",
        "form_btn_cancel": "Batal",
        "form_btn_save": "Simpan ke Perpustakaan",
        "playlist_title": "Daftar Putar",
        "footer_picspeak": "PicSpeak (Berbicara)",
        "footer_vocadash": "VocaDash (Kosakata)",
        "footer_guide": "Panduan Pengguna",
        "footer_dev": "Tentang Pengembang",
        "footer_teacher": "Menu Guru",
        "footer_terms": "Syarat Penggunaan",
        "footer_privacy": "Kebijakan Privasi",
        "learn_back": "Kembali",
        "learn_share": "Bagikan",
        "tab_read": "Membaca",
        "tab_paced": "Beri Jeda",
        "tab_vanish": "Menghilang",
        "tab_shadow": "Shadowing",
        "btn_ai_voice": "Putar Suara AI",
        "score_accuracy": "Akurasi",
        "score_wpm": "WPM",
        "score_comp": "Pemahaman",
        "score_feedback": "Umpan Balik Belajar",
        "btn_submit_score": "Kirim Nilai ke Guru (Refleksi)",
        "label_your_voice": "Suara Anda",
        "msg_press_start": "*Tekan START untuk memulai",
        "label_target_text": "Teks Target",
        "btn_show_translation": "Tampilkan Terjemahan",
        "label_blank_level": "Tingkat Kosong",
        "label_target_wpm": "Target WPM",
        "label_translation": "Terjemahan",
        "btn_start_text": "START",
        "sidebar_playlist": "Daftar Putar",
        "chart_title": "Kemajuan Belajar",
        "chart_desc": "*Latihan setiap hari adalah kunci untuk skor yang lebih tinggi!",
        "profile_title": "Pendaftaran Profil",
        "profile_desc": "Silakan daftarkan informasi Anda untuk mengirim nilai. (Disimpan secara lokal di perangkat ini)",
        "profile_class": "Kelas",
        "profile_placeholder_class": "Cth: 1-A",
        "profile_num": "Nomor Absen",
        "profile_placeholder_num": "Cth: 15",
        "profile_name": "Nama",
        "profile_placeholder_name": "Cth: Budi Santoso",
        "profile_save": "Simpan dan Mulai",
        "ref_title": "Kirim Nilai",
        "ref_desc": "Refleksi latihan hari ini (Apa yang berjalan baik, apa yang sulit, dll.)",
        "ref_placeholder_text": "Cth: Saya fokus pada intonasi saat shadowing...",
        "ref_cancel": "Batal",
        "ref_submit": "Kirim Sekarang",
        "wpm_guide_title": "Panduan WPM",
        "wpm_guide_desc": "*WPM (Kata per Menit)",
        "wpm_80": "Lambat (Pemula)",
        "wpm_100": "Standar (Menengah)",
        "wpm_120": "Lancar (Percakapan sehari-hari)",
        "wpm_150": "Cepat (Berita/TOEIC)",
        "wpm_180": "Sangat Cepat (Kecepatan penutur asli)",
        "btn_close": "Tutup",
        "mode_guide_title": "Panduan Belajar 4 Langkah Copeak",
        "mode_guide_warning": "Langsung ke mode 'Beri Jeda' atau 'Menghilang' tidak akan efektif. Pahami teksnya 100% terlebih dahulu, lalu tingkatkan beban langkah demi langkah.",
        "mode_tag_1": "Pengenalan / Makna",
        "mode_sla": "🔬 Dasar SLA:",
        "mode_desc_1": "'Pemetaan Bentuk-Makna'. Dasar untuk menghubungkan teks, suara, dan makna di otak Anda.",
        "mode_check": "🤔 Cek Refleksi:",
        "mode_check_1": "'Apakah saya 100% memahami maknanya dan dapat membacanya dengan lancar tanpa tersendat?'",
        "mode_tag_2": "Kelancaran / Otomatisasi",
        "mode_desc_2": "'Otomatisasi'. Kecepatan visual yang dipaksakan mencegah Anda membaca mundur, melatih otak untuk memproses bahasa Inggris dalam urutan kata yang alami.",
        "mode_check_2": "'Apakah saya memahaminya dalam bahasa Inggris tanpa menerjemahkan? Apakah pelafalan saya menjadi tidak jelas karena kecepatan?'",
        "mode_tag_3": "Retensi / Internalisasi",
        "mode_desc_3": "'Latihan Mengingat'. Dengan menghilangkan petunjuk visual, kita memaksa memori kerja untuk mengingat kata, menanamkannya ke dalam memori jangka panjang.",
        "mode_check_3": "'Apakah saya menebak kata berikutnya dari konteks/tata bahasa, bukan hanya menghafal mati?'",
        "mode_tag_4": "Pemrosesan Fonologis Puncak",
        "mode_desc_4": "'Peningkatan Putaran Fonologis'. Meniru prosodi penutur asli sepenuhnya mengotomatiskan persepsi suara Anda, meningkatkan kemampuan berbicara dan mendengarkan.",
        "mode_check_4": "'Apakah suara saya tumpang tindih sempurna dengan model? Apakah saya membayangkan maknanya sambil fokus pada suara?'",
        "btn_start_learning": "Saya mengerti, mari mulai"
    },

    // 🇵🇭 タガログ語（フィリピン）
    "tl": {
        "head_title": "Copeak - English Shadowing & Reading Tool",
        "nav_my_library": "Aking Library",
        "warning_title": "Mahalagang Paunawa sa Pag-save ng Data",
        "warning_ipad_bold": "Mga gumagamit ng iPad / Mobile:",
        "warning_ipad_desc": "Paki-tap muna ang 'Add to Home Screen' mula sa menu ng iyong browser, at laging buksan ang app mula sa icon na iyon.",
        "warning_pc_bold": "Mga gumagamit ng PC:",
        "warning_pc_desc": "I-bookmark ang pahinang ito at laging gamitin ang parehong browser.",
        "teacher_title": "Teacher Settings: Pag-setup ng Pagkolekta ng Iskor",
        "teacher_desc": "2 hakbang para i-set up ang sistema. Kapag na-configure na, awtomatikong idaragdag ang feature na pagsumite ng iskor sa mga ibinahaging link.",
        "teacher_step1_title": "Kopyahin ang Form",
        "teacher_step1_desc": "I-click ang button sa ibaba para kopyahin ang master Google Form sa iyong Drive. (*Huwag i-edit ang mga tanong)",
        "teacher_step1_btn": "Kopyahin ang Master Form",
        "teacher_step2_title": "Irehistro ang URL",
        "teacher_step2_desc": "Buksan ang kinopyang form sa 'Send' mode, i-paste ang response URL (.../viewform) sa ibaba, at i-save.",
        "teacher_step2_btn": "I-save",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "Gumawa / Mag-edit ng Materyal",
        "form_label_title": "Pamagat",
        "form_placeholder_title": "Hal. Steve Jobs Speech",
        "form_label_language": "Wika",
        "form_label_audio": "Audio File (Opsyonal)",
        "form_audio_saved": "Naka-save na ang audio",
        "form_label_text": "Target na Teksto",
        "form_placeholder_eng": "I-paste ang English script dito",
        "form_label_translation": "Pagsasalin",
        "form_placeholder_jpn": "I-paste ang pagsasalin (Opsyonal)",
        "form_btn_cancel": "Kanselahin",
        "form_btn_save": "I-save sa Library",
        "playlist_title": "Playlist",
        "footer_picspeak": "PicSpeak (Pagsasalita)",
        "footer_vocadash": "VocaDash (Bokabularyo)",
        "footer_guide": "Gabay ng Gumagamit",
        "footer_dev": "Tungkol sa Developer",
        "footer_teacher": "Menu ng Guro",
        "footer_terms": "Mga Tuntunin sa Paggamit",
        "footer_privacy": "Patakaran sa Privacy",
        "learn_back": "Bumalik",
        "learn_share": "I-share",
        "tab_read": "Magbasa",
        "tab_paced": "May Bilis",
        "tab_vanish": "Nawawala",
        "tab_shadow": "Shadowing",
        "btn_ai_voice": "I-play ang AI Voice",
        "score_accuracy": "Katumpakan",
        "score_wpm": "WPM",
        "score_comp": "Pag-unawa",
        "score_feedback": "Feedback sa Pag-aaral",
        "btn_submit_score": "Isumite ang Iskor sa Guro (Pagninilay)",
        "label_your_voice": "Iyong Boses",
        "msg_press_start": "*I-press ang START para magsimula",
        "label_target_text": "Target na Teksto",
        "btn_show_translation": "Ipakita ang Pagsasalin",
        "label_blank_level": "Antas ng Blangko",
        "label_target_wpm": "Target na WPM",
        "label_translation": "Pagsasalin",
        "btn_start_text": "START",
        "sidebar_playlist": "Playlist",
        "chart_title": "Pag-unlad ng Pag-aaral",
        "chart_desc": "*Ang araw-araw na pagsasanay ang susi sa mas mataas na iskor!",
        "profile_title": "Pagpaparehistro ng Profile",
        "profile_desc": "Pakirehistro ang iyong impormasyon para makapagsumite ng iskor. (Naka-save sa device na ito)",
        "profile_class": "Seksyon/Klase",
        "profile_placeholder_class": "Hal. 1-A",
        "profile_num": "Numero ng Estudyante",
        "profile_placeholder_num": "Hal. 15",
        "profile_name": "Pangalan",
        "profile_placeholder_name": "Hal. Juan Dela Cruz",
        "profile_save": "I-save at Magsimula",
        "ref_title": "Isumite ang Iskor",
        "ref_desc": "Pagninilay sa pagsasanay ngayon (Ano ang naging maganda, ano ang naging mahirap, atbp.)",
        "ref_placeholder_text": "Hal. Nag-focus ako sa aking intonasyon habang nagsha-shadowing...",
        "ref_cancel": "Kanselahin",
        "ref_submit": "Isumite Ngayon",
        "wpm_guide_title": "Gabay sa WPM",
        "wpm_guide_desc": "*WPM (Words Per Minute)",
        "wpm_80": "Mabagal (Beginner)",
        "wpm_100": "Standard (Intermediate)",
        "wpm_120": "Matatas (Pang-araw-araw na pag-uusap)",
        "wpm_150": "Mabilis (Balita/TOEIC)",
        "wpm_180": "Napakabilis (Bilis ng Native)",
        "btn_close": "Isara",
        "mode_guide_title": "Gabay sa Pag-aaral ng Copeak (4 na Hakbang)",
        "mode_guide_warning": "Hindi epektibo ang pagtalon agad sa 'Paced' o 'Vanish'. Intindihin muna ang teksto nang 100%, saka dagdagan ang hirap nang paunti-unti.",
        "mode_tag_1": "Panimula / Kahulugan",
        "mode_sla": "🔬 Basehan sa SLA:",
        "mode_desc_1": "'Form-Meaning Mapping'. Ang pundasyon ng pagkonekta ng teksto, tunog, at kahulugan sa iyong utak.",
        "mode_check": "🤔 Pagninilay:",
        "mode_check_1": "'Naiintindihan ko ba ang kahulugan ng 100% at nababasa ko ba ito nang maayos na walang pag-utal?'",
        "mode_tag_2": "Pagiging Matatas / Automation",
        "mode_desc_2": "'Automatization'. Ang pilit na bilis ay pumipigil sa pagbabasa nang pabalik, at sinasanay ang utak na i-proseso ang Ingles sa natural nitong ayos.",
        "mode_check_2": "'Naiintindihan ko ba ito sa Ingles nang hindi isinasalin sa isip? Pumapangit ba ang bigkas ko dahil sa bilis?'",
        "mode_tag_3": "Pagtatanda / Internalization",
        "mode_desc_3": "'Retrieval Practice'. Sa pagtanggal ng visual hints, pinipilit nating alalahanin ng ating isip ang mga salita para mapunta ito sa long-term memory.",
        "mode_check_3": "'Hinuhulaan ko ba ang susunod na salita mula sa konteksto/grammar, kaysa sa pilit na pagmemorya lamang?'",
        "mode_tag_4": "Ultimate Phonological Loop",
        "mode_desc_4": "'Phonological Loop Enhancement'. Ang paggaya sa prosody ng native speaker ay awtomatikong nagpapa-improve sa iyong pagsasalita at pakikinig.",
        "mode_check_4": "'Sumasabay ba ang boses ko nang perpekto sa audio? Naiisip ko ba ang kahulugan habang naka-focus sa tunog?'",
        "btn_start_learning": "Naiintindihan ko, magsimula na tayo"
    },

    // 🇮🇳 ヒンディー語
    "hi": {
        "head_title": "Copeak - इंग्लिश शैडोइंग और रीडिंग टूल",
        "nav_my_library": "मेरी लाइब्रेरी",
        "warning_title": "डेटा सेव करने के लिए महत्वपूर्ण सूचना",
        "warning_ipad_bold": "iPad / मोबाइल यूज़र्स:",
        "warning_ipad_desc": "कृपया पहले अपने ब्राउज़र मेन्यू से 'Add to Home Screen' पर टैप करें, और हमेशा उसी आइकन से ऐप खोलें।",
        "warning_pc_bold": "PC यूज़र्स:",
        "warning_pc_desc": "कृपया इस पेज को बुकमार्क करें और हमेशा एक ही ब्राउज़र का उपयोग करें।",
        "teacher_title": "टीचर सेटिंग्स: स्कोर कलेक्शन सेटअप",
        "teacher_desc": "सिस्टम सेटअप करने के 2 कदम। एक बार सेट होने के बाद, आपके शेयर किए गए लिंक में स्कोर सबमिशन फीचर अपने आप जुड़ जाएगा।",
        "teacher_step1_title": "फॉर्म कॉपी करें",
        "teacher_step1_desc": "मास्टर Google Form को अपने Drive में कॉपी करने के लिए नीचे दिए गए बटन पर क्लिक करें। (*कृपया प्रश्नों को एडिट न करें)",
        "teacher_step1_btn": "मास्टर फॉर्म कॉपी करें",
        "teacher_step2_title": "URL रजिस्टर करें",
        "teacher_step2_desc": "कॉपी किए गए फॉर्म को 'Send' मोड में खोलें, रिस्पॉन्स URL (.../viewform) नीचे पेस्ट करें, और सेव करें।",
        "teacher_step2_btn": "सेव करें",
        "teacher_placeholder_url": "https://docs.google.com/forms/...",
        "form_title": "मटीरियल बनाएँ / एडिट करें",
        "form_label_title": "शीर्षक (Title)",
        "form_placeholder_title": "उदा. Steve Jobs Speech",
        "form_label_language": "भाषा",
        "form_label_audio": "ऑडियो फाइल (वैकल्पिक)",
        "form_audio_saved": "ऑडियो पहले से सेव है",
        "form_label_text": "टारगेट टेक्स्ट",
        "form_placeholder_eng": "इंग्लिश स्क्रिप्ट यहाँ पेस्ट करें",
        "form_label_translation": "अनुवाद (Translation)",
        "form_placeholder_jpn": "मातृभाषा में अनुवाद पेस्ट करें (वैकल्पिक)",
        "form_btn_cancel": "रद्द करें",
        "form_btn_save": "लाइब्रेरी में सेव करें",
        "playlist_title": "प्लेलिस्ट",
        "footer_picspeak": "PicSpeak (स्पीकिंग)",
        "footer_vocadash": "VocaDash (शब्दावली)",
        "footer_guide": "यूज़र गाइड",
        "footer_dev": "डेवलपर के बारे में",
        "footer_teacher": "टीचर मेन्यू",
        "footer_terms": "उपयोग की शर्तें",
        "footer_privacy": "प्राइवेसी पॉलिसी",
        "learn_back": "वापस",
        "learn_share": "शेयर करें",
        "tab_read": "पढ़ें (Read)",
        "tab_paced": "पेस्ड (Paced)",
        "tab_vanish": "वैनिश (Vanish)",
        "tab_shadow": "शैडोइंग (Shadowing)",
        "btn_ai_voice": "AI आवाज़ चलाएँ",
        "score_accuracy": "सटीकता (Accuracy)",
        "score_wpm": "WPM",
        "score_comp": "समझ (Comprehension)",
        "score_feedback": "लर्निंग फीडबैक",
        "btn_submit_score": "टीचर को स्कोर भेजें (रिफ्लेक्शन)",
        "label_your_voice": "आपकी आवाज़",
        "msg_press_start": "*शुरू करने के लिए START दबाएँ",
        "label_target_text": "टारगेट टेक्स्ट",
        "btn_show_translation": "अनुवाद दिखाएँ",
        "label_blank_level": "ब्लैंक लेवल",
        "label_target_wpm": "टारगेट WPM",
        "label_translation": "अनुवाद",
        "btn_start_text": "START",
        "sidebar_playlist": "प्लेलिस्ट",
        "chart_title": "लर्निंग प्रोग्रेस",
        "chart_desc": "*रोज़ाना प्रैक्टिस ही अच्छे स्कोर की कुंजी है!",
        "profile_title": "प्रोफाइल रजिस्ट्रेशन",
        "profile_desc": "स्कोर भेजने के लिए कृपया अपनी जानकारी दर्ज करें। (यह इसी डिवाइस में सेव होगी)",
        "profile_class": "क्लास",
        "profile_placeholder_class": "उदा. 1-A",
        "profile_num": "रोल नंबर",
        "profile_placeholder_num": "उदा. 15",
        "profile_name": "नाम",
        "profile_placeholder_name": "उदा. राहुल शर्मा",
        "profile_save": "सेव करें और शुरू करें",
        "ref_title": "स्कोर सबमिट करें",
        "ref_desc": "आज की प्रैक्टिस पर विचार (क्या अच्छा रहा, क्या मुश्किल था, आदि)",
        "ref_placeholder_text": "उदा. मैंने शैडोइंग के दौरान अपने इंटोनेशन पर ध्यान दिया...",
        "ref_cancel": "रद्द करें",
        "ref_submit": "अभी भेजें",
        "wpm_guide_title": "WPM गाइड",
        "wpm_guide_desc": "*WPM (प्रति मिनट शब्द)",
        "wpm_80": "धीमा (शुरुआती)",
        "wpm_100": "सामान्य (इंटरमीडिएट)",
        "wpm_120": "धाराप्रवाह (रोज़मर्रा की बातचीत)",
        "wpm_150": "तेज़ (न्यूज़/TOEIC)",
        "wpm_180": "बहुत तेज़ (नेटिव स्पीड)",
        "btn_close": "बंद करें",
        "mode_guide_title": "Copeak 4-स्टेप लर्निंग गाइड",
        "mode_guide_warning": "सीधे 'Paced' या 'Vanish' पर जाना असरदार नहीं होगा। पहले टेक्स्ट को 100% समझें, फिर धीरे-धीरे कठिनाई बढ़ाएँ।",
        "mode_tag_1": "परिचय / अर्थ",
        "mode_sla": "🔬 SLA आधार:",
        "mode_desc_1": "'फॉर्म-मीनिंग मैपिंग'। दिमाग में टेक्स्ट, ध्वनि और अर्थ को जोड़ने की नींव।",
        "mode_check": "🤔 रिफ्लेक्शन चेक:",
        "mode_check_1": "'क्या मैं अर्थ 100% समझता हूँ और बिना अटके आसानी से पढ़ सकता हूँ?'",
        "mode_tag_2": "प्रवाह / ऑटोमेशन",
        "mode_desc_2": "'ऑटोमेटाइज़ेशन'। एक निश्चित गति आपको पीछे मुड़कर पढ़ने से रोकती है, दिमाग को इंग्लिश के असली क्रम में सोचने की ट्रेनिंग देती है।",
        "mode_check_2": "'क्या मैं बिना अनुवाद किए इंग्लिश में ही समझ रहा हूँ? क्या जल्दबाज़ी में मेरा उच्चारण खराब हो रहा है?'",
        "mode_tag_3": "याद रखना / इंटरनलाइज़ेशन",
        "mode_desc_3": "'रिट्रीवल प्रैक्टिस'। विज़ुअल हिंट्स हटाकर, हम वर्किंग मेमोरी को शब्द याद करने के लिए मजबूर करते हैं, जिससे वे लॉन्ग-टर्म मेमोरी में चले जाते हैं।",
        "mode_check_3": "'क्या मैं सिर्फ रटने के बजाय संदर्भ/ग्रामर से अगले शब्द का अनुमान लगा रहा हूँ?'",
        "mode_tag_4": "अल्टीमेट फोनोलॉजिकल लूप",
        "mode_desc_4": "'फोनोलॉजिकल लूप एन्हांसमेंट'। नेटिव स्पीकर की आवाज़ की नकल करने से आपकी बोलने और सुनने की क्षमता अपने आप बेहतर हो जाती है।",
        "mode_check_4": "'क्या मेरी आवाज़ मॉडल के साथ बिल्कुल मेल खा रही है? क्या मैं आवाज़ पर ध्यान देते हुए अर्थ की कल्पना कर रहा हूँ?'",
        "btn_start_learning": "मैं समझ गया, चलिए शुरू करते हैं"
    }
};

// ==========================================
// ★ 翻訳実行・言語切り替えエンジン
// ==========================================

// 選択された言語を画面全体に適用する関数
function changeAppLanguage(langCode) {
    if (!i18n[langCode]) return; // 辞書にない言語が選ばれたら何もしない
    
    // 1. 選んだ言語をブラウザ（localStorage）に記憶させる
    localStorage.setItem('copeak_lang', langCode);

    // 2. data-i18n（通常のテキスト）の入れ替え
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (i18n[langCode][key]) {
            el.innerText = i18n[langCode][key];
        }
    });

    // 3. data-i18n-placeholder（入力枠の薄い文字）の入れ替え
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (i18n[langCode][key]) {
            el.setAttribute('placeholder', i18n[langCode][key]);
        }
    });

    console.log(`Copeak UI Language switched to: ${langCode}`);
}

// ページが読み込まれた時に一番最初に動く処理
window.addEventListener('DOMContentLoaded', () => {
    // 以前保存した言語があるかチェック（なければ日本語 'ja'）
    let savedLang = localStorage.getItem('copeak_lang');
    
    if (!savedLang) {
        // もし保存された言語がなければ、ブラウザの基本言語設定をチェックして自動判定する
        const userLang = navigator.language || navigator.userLanguage; 
        if (userLang.startsWith('en')) savedLang = 'en';
        else if (userLang.startsWith('zh')) savedLang = 'zh-TW';
        else if (userLang.startsWith('vi')) savedLang = 'vi';
        else if (userLang.startsWith('id')) savedLang = 'id';
        else if (userLang.startsWith('tl')) savedLang = 'tl';
        else if (userLang.startsWith('hi')) savedLang = 'hi';
        else savedLang = 'ja'; // その他は全部日本語
    }

    // セレクトボックス（ドロップダウン）の表示を、選択中の言語に合わせる
    const langSelector = document.getElementById('appLangSelector');
    if (langSelector) {
        langSelector.value = savedLang;
    }

    // 実際に文字を切り替える関数を発動
    changeAppLanguage(savedLang);
});